spring:
  profiles: 
    active: 
    - dev
---
server: 
  port: 8001
spring:
  profiles: dev
  application:
    name: micservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01
    username: root
    password: abc123
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
      validation-query: SELECT 1
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.aslipi.micservicecloud.pojo
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: micservicecloud-dept8001
    prefer-ip-address: true

info:
  app.name: aslipi-micservicecloud-springcloudconfig01
  company.name: www.aslipi.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server: 
  port: 8001
spring:
  profiles: test
  application:
    name: micservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloudDB02
    username: root
    password: abc123
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
      validation-query: SELECT 1
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.aslipi.micservicecloud.pojo
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: micservicecloud-dept8002
    prefer-ip-address: true

info:
  app.name: aslipi-micservicecloud-springcloudconfig02
  company.name: www.aslipi.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$